<?php
    /* -*- coding: utf-8; mode: php; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- vim:fenc=utf-8:filetype=php:et:sw=4:ts=4:sts=4 */
    /* Copyright (c) 2004, OpenDarwin. */
    /* Copyright (c) 2004-2007, The MacPorts Project. */
?>


        <div id="footer">

            <p><a href="https://validator.w3.org/check?uri=referer"><img src="img/W3C_HTML5_certified.png" height="31" width="88" alt="Valid HTML 5" /></a>
            <a href="https://jigsaw.w3.org/css-validator/check/referer"><img src="img/vcss.png" alt="Valid CSS!" /></a></p>

            <p>Copyright &#xA9; 2002&#x2013;<?php print date("Y"); ?>, <a href="https://www.macports.org">The MacPorts Project</a>.
            All rights reserved.
            Content delivery accelerated by <a href="https://www.stackpath.com/">StackPath</a>.</p>

        </div>

    </body>

</html>
