<?php
    /* -*- coding: utf-8; mode: php; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- vim:fenc=utf-8:filetype=php:et:sw=4:ts=4:sts=4 */
    /* $Id$ */
    /* Copyright (c) 2004, OpenDarwin. */
    /* Copyright (c) 2004-2007, The MacPorts Project. */
?>


        <div id="footer">
        
            <p><a href="http://validator.w3.org/check?uri=referer"><img src="img/valid-xhtml11-blue.png" alt="Valid XHTML 1.1" /></a>
            <a href="http://jigsaw.w3.org/css-validator/check/referer"><img src="img/vcss.png" alt="Valid CSS!" /></a></p>
            
            <p>Copyright &#xA9; 2002&#x2013;<?php print date("Y"); ?>, <a href="https://www.macports.org">The MacPorts Project</a>.
            Content delivery accelerated by <a href="https://www.maxcdn.com">MaxCDN</a>.
            All rights reserved.</p>

        </div>

    </body>

</html>
