<?php
    /* -*- coding: utf-8; mode: php; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- vim:fenc=utf-8:filetype=php:et:sw=4:ts=4:sts=4 */
    /* Copyright (c) 2004, OpenDarwin. */
    /* Copyright (c) 2004-2007, The MacPorts Project. */
?>


        <div id="footer">

            <p>Copyright &#xA9; 2002&#x2013;<?php print date("Y"); ?>, <a href="https://www.macports.org">The MacPorts Project</a>.
            All rights reserved.</p>

        </div>

    </body>

</html>
